apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
  namespace: hello-python
spec:
  selector:
    name: hello-python-service
  ports:
  - name: https
    port: 7000
    targetPort: 7000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python-service
  namespace: hello-python
spec:
  selector:
    matchLabels:
      name: hello-python-service
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-python-service
    spec:
      containers:
      - name: espadin-tfarooqn-python-prueba
        image: localhost:32000/espadin_tfarooqn_python_prueba:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7000